import type { Collection, Db } from "mongodb";

import { getMongoDb } from "./connection";
import type {
  AlertDoc,
  AppointmentDoc,
  CareGoalDoc,
  CarePlanDoc,
  ConversationDoc,
  ConversationMemberDoc,
  CommunicationLogDoc,
  EmergencyDoc,
  EducationResourceDoc,
  FcmTokenDoc,
  AssignmentDoc,
  NotificationDoc,
  NotificationDeliveryDoc,
  AuditLogDoc,
  OutboxJobDoc,
  DomainEventDoc,
  IdempotencyKeyDoc,
  MedicationDoc,
  MedicationLogDoc,
  MessageDoc,
  PatientProfileDoc,
  OutcomeSnapshotDoc,
  StaffProfileDoc,
  SymptomCheckinDoc,
  UserDoc,
  VisitScheduleDoc,
  VitalsReadingDoc,
} from "./types";

export const COLLECTIONS = {
  users: "users",
  patientProfiles: "patient_profiles",
  staffProfiles: "staff_profiles",
  vitalsReadings: "vitals_readings",
  medications: "medications",
  medicationLogs: "medication_logs",
  alerts: "alerts",
  messages: "messages",
  conversations: "conversations",
  conversationMembers: "conversation_members",
  appointments: "appointments",
  symptomCheckins: "symptom_checkins",
  carePlans: "care_plans",
  visitSchedules: "visit_schedules",
  educationResources: "education_resources",
  communicationLogs: "communication_logs",
  outcomeSnapshots: "outcome_snapshots",
  emergencies: "emergencies",
  fcmTokens: "fcm_tokens",
  assignments: "assignments",
  notifications: "notifications",
  notificationDeliveries: "notification_deliveries",
  auditLogs: "audit_logs",
  outboxJobs: "outbox_jobs",
  domainEvents: "domain_events",
  idempotencyKeys: "idempotency_keys",
} as const;

export async function collections(db?: Db) {
  const database = db ?? (await getMongoDb());
  return {
    users: database.collection<UserDoc>(COLLECTIONS.users),
    patientProfiles: database.collection<PatientProfileDoc>(COLLECTIONS.patientProfiles),
    staffProfiles: database.collection<StaffProfileDoc>(COLLECTIONS.staffProfiles),
    vitalsReadings: database.collection<VitalsReadingDoc>(COLLECTIONS.vitalsReadings),
    medications: database.collection<MedicationDoc>(COLLECTIONS.medications),
    medicationLogs: database.collection<MedicationLogDoc>(COLLECTIONS.medicationLogs),
    alerts: database.collection<AlertDoc>(COLLECTIONS.alerts),
    messages: database.collection<MessageDoc>(COLLECTIONS.messages),
    conversations: database.collection<ConversationDoc>(COLLECTIONS.conversations),
    conversationMembers: database.collection<ConversationMemberDoc>(
      COLLECTIONS.conversationMembers,
    ),
    appointments: database.collection<AppointmentDoc>(COLLECTIONS.appointments),
    symptomCheckins: database.collection<SymptomCheckinDoc>(COLLECTIONS.symptomCheckins),
    carePlans: database.collection<CarePlanDoc>(COLLECTIONS.carePlans),
    visitSchedules: database.collection<VisitScheduleDoc>(COLLECTIONS.visitSchedules),
    educationResources: database.collection<EducationResourceDoc>(COLLECTIONS.educationResources),
    communicationLogs: database.collection<CommunicationLogDoc>(COLLECTIONS.communicationLogs),
    outcomeSnapshots: database.collection<OutcomeSnapshotDoc>(COLLECTIONS.outcomeSnapshots),
    emergencies: database.collection<EmergencyDoc>(COLLECTIONS.emergencies),
    fcmTokens: database.collection<FcmTokenDoc>(COLLECTIONS.fcmTokens),
    assignments: database.collection<AssignmentDoc>(COLLECTIONS.assignments),
    notifications: database.collection<NotificationDoc>(COLLECTIONS.notifications),
    notificationDeliveries: database.collection<NotificationDeliveryDoc>(
      COLLECTIONS.notificationDeliveries,
    ),
    auditLogs: database.collection<AuditLogDoc>(COLLECTIONS.auditLogs),
    outboxJobs: database.collection<OutboxJobDoc>(COLLECTIONS.outboxJobs),
    domainEvents: database.collection<DomainEventDoc>(COLLECTIONS.domainEvents),
    idempotencyKeys: database.collection<IdempotencyKeyDoc>(COLLECTIONS.idempotencyKeys),
  };
}

export type Collections = Awaited<ReturnType<typeof collections>>;
export type { Collection };
