/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as NurseIndexRouteImport } from './routes/nurse.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PatientVitalsRouteImport } from './routes/patient.vitals'
import { Route as PatientMedicationsRouteImport } from './routes/patient.medications'
import { Route as PatientEmergencyRouteImport } from './routes/patient.emergency'
import { Route as PatientChatRouteImport } from './routes/patient.chat'
import { Route as PatientAssistantRouteImport } from './routes/patient.assistant'
import { Route as NursePatientsRouteImport } from './routes/nurse.patients'
import { Route as NurseChatRouteImport } from './routes/nurse.chat'
import { Route as NurseAlertsRouteImport } from './routes/nurse.alerts'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor.prescriptions'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const NurseIndexRoute = NurseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NurseRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PatientVitalsRoute = PatientVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicationsRoute = PatientMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientEmergencyRoute = PatientEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => PatientRoute,
} as any)
const PatientChatRoute = PatientChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAssistantRoute = PatientAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PatientRoute,
} as any)
const NursePatientsRoute = NursePatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => NurseRoute,
} as any)
const NurseChatRoute = NurseChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => NurseRoute,
} as any)
const NurseAlertsRoute = NurseAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => NurseRoute,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/nurse/alerts': typeof NurseAlertsRoute
  '/nurse/chat': typeof NurseChatRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/vitals': typeof PatientVitalsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/nurse/alerts': typeof NurseAlertsRoute
  '/nurse/chat': typeof NurseChatRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/vitals': typeof PatientVitalsRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/nurse': typeof NurseIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/doctor': typeof DoctorRouteWithChildren
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/nurse/alerts': typeof NurseAlertsRoute
  '/nurse/chat': typeof NurseChatRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/vitals': typeof PatientVitalsRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/nurse'
    | '/patient'
    | '/admin/analytics'
    | '/admin/assignments'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/nurse/alerts'
    | '/nurse/chat'
    | '/nurse/patients'
    | '/patient/assistant'
    | '/patient/chat'
    | '/patient/emergency'
    | '/patient/medications'
    | '/patient/vitals'
    | '/admin/'
    | '/doctor/'
    | '/nurse/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/assignments'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/nurse/alerts'
    | '/nurse/chat'
    | '/nurse/patients'
    | '/patient/assistant'
    | '/patient/chat'
    | '/patient/emergency'
    | '/patient/medications'
    | '/patient/vitals'
    | '/admin'
    | '/doctor'
    | '/nurse'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/nurse'
    | '/patient'
    | '/admin/analytics'
    | '/admin/assignments'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/nurse/alerts'
    | '/nurse/chat'
    | '/nurse/patients'
    | '/patient/assistant'
    | '/patient/chat'
    | '/patient/emergency'
    | '/patient/medications'
    | '/patient/vitals'
    | '/admin/'
    | '/doctor/'
    | '/nurse/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DoctorRoute: typeof DoctorRouteWithChildren
  NurseRoute: typeof NurseRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/nurse/': {
      id: '/nurse/'
      path: '/'
      fullPath: '/nurse/'
      preLoaderRoute: typeof NurseIndexRouteImport
      parentRoute: typeof NurseRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/patient/vitals': {
      id: '/patient/vitals'
      path: '/vitals'
      fullPath: '/patient/vitals'
      preLoaderRoute: typeof PatientVitalsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medications': {
      id: '/patient/medications'
      path: '/medications'
      fullPath: '/patient/medications'
      preLoaderRoute: typeof PatientMedicationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/emergency': {
      id: '/patient/emergency'
      path: '/emergency'
      fullPath: '/patient/emergency'
      preLoaderRoute: typeof PatientEmergencyRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/chat': {
      id: '/patient/chat'
      path: '/chat'
      fullPath: '/patient/chat'
      preLoaderRoute: typeof PatientChatRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/assistant': {
      id: '/patient/assistant'
      path: '/assistant'
      fullPath: '/patient/assistant'
      preLoaderRoute: typeof PatientAssistantRouteImport
      parentRoute: typeof PatientRoute
    }
    '/nurse/patients': {
      id: '/nurse/patients'
      path: '/patients'
      fullPath: '/nurse/patients'
      preLoaderRoute: typeof NursePatientsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/chat': {
      id: '/nurse/chat'
      path: '/chat'
      fullPath: '/nurse/chat'
      preLoaderRoute: typeof NurseChatRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/alerts': {
      id: '/nurse/alerts'
      path: '/alerts'
      fullPath: '/nurse/alerts'
      preLoaderRoute: typeof NurseAlertsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DoctorRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface NurseRouteChildren {
  NurseAlertsRoute: typeof NurseAlertsRoute
  NurseChatRoute: typeof NurseChatRoute
  NursePatientsRoute: typeof NursePatientsRoute
  NurseIndexRoute: typeof NurseIndexRoute
}

const NurseRouteChildren: NurseRouteChildren = {
  NurseAlertsRoute: NurseAlertsRoute,
  NurseChatRoute: NurseChatRoute,
  NursePatientsRoute: NursePatientsRoute,
  NurseIndexRoute: NurseIndexRoute,
}

const NurseRouteWithChildren = NurseRoute._addFileChildren(NurseRouteChildren)

interface PatientRouteChildren {
  PatientAssistantRoute: typeof PatientAssistantRoute
  PatientChatRoute: typeof PatientChatRoute
  PatientEmergencyRoute: typeof PatientEmergencyRoute
  PatientMedicationsRoute: typeof PatientMedicationsRoute
  PatientVitalsRoute: typeof PatientVitalsRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAssistantRoute: PatientAssistantRoute,
  PatientChatRoute: PatientChatRoute,
  PatientEmergencyRoute: PatientEmergencyRoute,
  PatientMedicationsRoute: PatientMedicationsRoute,
  PatientVitalsRoute: PatientVitalsRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DoctorRoute: DoctorRouteWithChildren,
  NurseRoute: NurseRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
