/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientVitalsRouteImport } from './routes/patient.vitals'
import { Route as PatientMedicationsRouteImport } from './routes/patient.medications'
import { Route as PatientEmergencyRouteImport } from './routes/patient.emergency'
import { Route as PatientChatRouteImport } from './routes/patient.chat'
import { Route as PatientAssistantRouteImport } from './routes/patient.assistant'

const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientVitalsRoute = PatientVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicationsRoute = PatientMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientEmergencyRoute = PatientEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => PatientRoute,
} as any)
const PatientChatRoute = PatientChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAssistantRoute = PatientAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/doctor': typeof DoctorRoute
  '/nurse': typeof NurseRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/vitals': typeof PatientVitalsRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/doctor': typeof DoctorRoute
  '/nurse': typeof NurseRoute
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/vitals': typeof PatientVitalsRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/doctor': typeof DoctorRoute
  '/nurse': typeof NurseRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/assistant': typeof PatientAssistantRoute
  '/patient/chat': typeof PatientChatRoute
  '/patient/emergency': typeof PatientEmergencyRoute
  '/patient/medications': typeof PatientMedicationsRoute
  '/patient/vitals': typeof PatientVitalsRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/nurse'
    | '/patient'
    | '/patient/assistant'
    | '/patient/chat'
    | '/patient/emergency'
    | '/patient/medications'
    | '/patient/vitals'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/doctor'
    | '/nurse'
    | '/patient/assistant'
    | '/patient/chat'
    | '/patient/emergency'
    | '/patient/medications'
    | '/patient/vitals'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/nurse'
    | '/patient'
    | '/patient/assistant'
    | '/patient/chat'
    | '/patient/emergency'
    | '/patient/medications'
    | '/patient/vitals'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DoctorRoute: typeof DoctorRoute
  NurseRoute: typeof NurseRoute
  PatientRoute: typeof PatientRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/vitals': {
      id: '/patient/vitals'
      path: '/vitals'
      fullPath: '/patient/vitals'
      preLoaderRoute: typeof PatientVitalsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medications': {
      id: '/patient/medications'
      path: '/medications'
      fullPath: '/patient/medications'
      preLoaderRoute: typeof PatientMedicationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/emergency': {
      id: '/patient/emergency'
      path: '/emergency'
      fullPath: '/patient/emergency'
      preLoaderRoute: typeof PatientEmergencyRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/chat': {
      id: '/patient/chat'
      path: '/chat'
      fullPath: '/patient/chat'
      preLoaderRoute: typeof PatientChatRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/assistant': {
      id: '/patient/assistant'
      path: '/assistant'
      fullPath: '/patient/assistant'
      preLoaderRoute: typeof PatientAssistantRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface PatientRouteChildren {
  PatientAssistantRoute: typeof PatientAssistantRoute
  PatientChatRoute: typeof PatientChatRoute
  PatientEmergencyRoute: typeof PatientEmergencyRoute
  PatientMedicationsRoute: typeof PatientMedicationsRoute
  PatientVitalsRoute: typeof PatientVitalsRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAssistantRoute: PatientAssistantRoute,
  PatientChatRoute: PatientChatRoute,
  PatientEmergencyRoute: PatientEmergencyRoute,
  PatientMedicationsRoute: PatientMedicationsRoute,
  PatientVitalsRoute: PatientVitalsRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DoctorRoute: DoctorRoute,
  NurseRoute: NurseRoute,
  PatientRoute: PatientRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
